        ;------------------------------------------------------------------------
        ; DOSYA: ORNEK.MAC
        ; Bu dosya harici macro’ların yer aldığı bir dosyadır.
        ;------------------------------------------------------------------------

        ;------------------------------------------------------------------------
        ; INT 10H yardımıyla ekran silmeyi sağlayan macro kodu
        ;------------------------------------------------------------------------
SIL     MACRO
        MOV CX, 0000H    ; Ekranın sol üst köşesi satır/sütun adresi
        MOV DX, 184FH    ; Ekranın sağ alt köşesi satır/sütun adresi
        MOV BH, 07H      ; attribute byte
        MOV AX, 0600H    ; AH = 06H pencereyi yukarı kaydır
        INT 10H          ; 10H numaralı kesmeyi çağır
        ENDM
        ;------------------------------------------------------------------------
        ; INT 21H yardımıyla ekrana mesaj yazdıran macro
        ;------------------------------------------------------------------------
YAZDIR  MACRO text
        LEA DX, text     ; DX yazdırılacak mesajın başını göstermeli
        MOV AH, 09H      ; AH = 09H ekrana mesaj yaz 
        INT 21H          ; 21H numaralı kesmeyi çağır 
        ENDM
