	EXTRN  _dcalc: NEAR
_DATA 	SEGMENT WORD PUBLIC 'DATA'
IMAX	DW ?
XVAL	DW 10 DUP(?)
ANS	DW 2 DUP(?) 
_DATA	ENDS
_TEXT	SEGMENT BYTE PUBLIC 'CODE'
	ASSUME CS:_TEXT
BASLA	PROC NEAR
	MOV AX, 421
	PUSH AX
	PUSH IMAX
	LEA AX, XVAL
	PUSH AX
	CALL _dcalc
	ADD SP,6
	MOV ANS, AX
	MOV ANS+2, DX
	INT 20H
BASLA	ENDP
_TEXT	ENDS
	END BASLA
